import type { LevelDefinition } from '../models/types';
import { horizontalPath } from './helpers';

export const level3: LevelDefinition = {
  id: 'level3',
  name: 'L3: Friendly Fire',
  brief: 'You cannot touch the camera. Reroute the turret onto a drone.',
  map: {
    width: 13,
    height: 9,
    walls: [],
  },
  entry: { x: 1, y: 5 },
  exit: { x: 11, y: 5 },
  playerPath: horizontalPath(5, 1, 11),
  devices: [
    {
      id: 'C3',
      type: 'camera',
      x: 4,
      y: 2,
      enabled: true,
      range: 3,
      facing: 'down',
      disabledUntilTick: null,
    },
    {
      id: 'D3',
      type: 'door',
      x: 3,
      y: 5,
      enabled: true,
      isOpen: false,
    },
    {
      id: 'T3',
      type: 'turret',
      x: 8,
      y: 2,
      enabled: true,
      range: 7,
      lockDelay: 3,
      alarmTrigger: 'RED',
      desiredTargetId: null,
      currentTargetId: null,
      lockTicks: 0,
    },
    {
      id: 'DR3',
      type: 'drone',
      x: 8,
      y: 4,
      enabled: true,
      alive: true,
      path: [
        { x: 8, y: 4 },
        { x: 9, y: 4 },
        { x: 9, y: 3 },
        { x: 8, y: 3 },
      ],
      pathIndex: 0,
      stepInterval: 1,
      stepTimer: 0,
    },
    {
      id: 'A3',
      type: 'alarm',
      x: 0,
      y: 0,
      enabled: true,
      state: 'GREEN',
      baseEscalationTicks: 3,
      redAtTick: null,
      manualDelayBuffer: 0,
    },
    {
      id: 'TERM3',
      type: 'terminal',
      x: 1,
      y: 7,
      enabled: true,
    },
  ],
  networkScope: ['D3', 'T3', 'DR3'],
  constraints: {
    maxLines: 4,
    maxCommands: 4,
    maxDelayTicks: 20,
    tickLimit: 70,
  },
  suggestedScript: `door("D3").open()\nturret("T3").retarget("DR3")`,
};
