import type { LevelDefinition } from '../models/types';
import { horizontalPath } from './helpers';

export const level5: LevelDefinition = {
  id: 'level5',
  name: 'L5: Tight Budget',
  brief: 'Two doors, two cameras, strict command budget.',
  map: {
    width: 16,
    height: 10,
    walls: [],
  },
  entry: { x: 1, y: 5 },
  exit: { x: 14, y: 5 },
  playerPath: horizontalPath(5, 1, 14),
  devices: [
    {
      id: 'C5A',
      type: 'camera',
      x: 2,
      y: 2,
      enabled: true,
      range: 5,
      facing: 'down',
      disabledUntilTick: null,
    },
    {
      id: 'C5B',
      type: 'camera',
      x: 9,
      y: 2,
      enabled: true,
      range: 5,
      facing: 'down',
      disabledUntilTick: null,
    },
    {
      id: 'D5A',
      type: 'door',
      x: 4,
      y: 5,
      enabled: true,
      isOpen: false,
    },
    {
      id: 'D5B',
      type: 'door',
      x: 10,
      y: 5,
      enabled: true,
      isOpen: false,
    },
    {
      id: 'T5',
      type: 'turret',
      x: 11,
      y: 2,
      enabled: true,
      range: 9,
      lockDelay: 3,
      alarmTrigger: 'RED',
      desiredTargetId: null,
      currentTargetId: null,
      lockTicks: 0,
    },
    {
      id: 'DR5',
      type: 'drone',
      x: 12,
      y: 3,
      enabled: true,
      alive: true,
      path: [
        { x: 12, y: 3 },
        { x: 12, y: 2 },
        { x: 11, y: 2 },
        { x: 11, y: 3 },
      ],
      pathIndex: 0,
      stepInterval: 1,
      stepTimer: 0,
    },
    {
      id: 'A5',
      type: 'alarm',
      x: 0,
      y: 0,
      enabled: true,
      state: 'GREEN',
      baseEscalationTicks: 2,
      redAtTick: null,
      manualDelayBuffer: 0,
    },
    {
      id: 'TERM5',
      type: 'terminal',
      x: 1,
      y: 8,
      enabled: true,
    },
  ],
  networkScope: ['C5A', 'C5B', 'D5A', 'D5B', 'T5', 'DR5'],
  constraints: {
    tickLimit: 120,
  },
};
