import type { LevelDefinition } from '../models/types';
import { horizontalPath } from './helpers';

export const level4: LevelDefinition = {
  id: 'level4',
  name: 'L4: Sequencer',
  brief: 'Short disable windows force timed sequencing with wait().',
  map: {
    width: 15,
    height: 9,
    walls: [],
  },
  entry: { x: 1, y: 4 },
  exit: { x: 13, y: 4 },
  playerPath: horizontalPath(4, 1, 13),
  devices: [
    {
      id: 'C4A',
      type: 'camera',
      x: 3,
      y: 1,
      enabled: true,
      range: 5,
      facing: 'down',
      disabledUntilTick: null,
    },
    {
      id: 'C4B',
      type: 'camera',
      x: 10,
      y: 1,
      enabled: true,
      range: 5,
      facing: 'down',
      disabledUntilTick: null,
    },
    {
      id: 'D4',
      type: 'door',
      x: 6,
      y: 4,
      enabled: true,
      isOpen: false,
    },
    {
      id: 'T4',
      type: 'turret',
      x: 11,
      y: 2,
      enabled: true,
      range: 8,
      lockDelay: 3,
      alarmTrigger: 'RED',
      desiredTargetId: null,
      currentTargetId: null,
      lockTicks: 0,
    },
    {
      id: 'DR4',
      type: 'drone',
      x: 12,
      y: 2,
      enabled: true,
      alive: true,
      path: [
        { x: 12, y: 2 },
        { x: 12, y: 3 },
        { x: 11, y: 3 },
        { x: 11, y: 2 },
      ],
      pathIndex: 0,
      stepInterval: 1,
      stepTimer: 0,
    },
    {
      id: 'A4',
      type: 'alarm',
      x: 0,
      y: 0,
      enabled: true,
      state: 'GREEN',
      baseEscalationTicks: 2,
      redAtTick: null,
      manualDelayBuffer: 0,
    },
    {
      id: 'TERM4',
      type: 'terminal',
      x: 1,
      y: 7,
      enabled: true,
    },
  ],
  networkScope: ['C4A', 'C4B', 'D4', 'T4', 'DR4'],
  constraints: {
    tickLimit: 95,
  },
  suggestedScript: `camera("C4A").disable(6)\ndoor("D4").open()\nwait(6)\ncamera("C4B").disable(6)`,
};
