import type { LevelDefinition } from '../models/types';
import { horizontalPath } from './helpers';

export const level3: LevelDefinition = {
  id: 'level3',
  name: 'L3: First Turret',
  brief: 'If the camera sees you, the turret pivots and fires. Disable the camera and open the route.',
  map: {
    width: 13,
    height: 9,
    walls: [],
  },
  entry: { x: 1, y: 5 },
  exit: { x: 11, y: 5 },
  playerPath: horizontalPath(5, 1, 11),
  devices: [
    {
      id: 'C3',
      type: 'camera',
      x: 4,
      y: 2,
      enabled: true,
      range: 3,
      facing: 'down',
      disabledUntilTick: null,
    },
    {
      id: 'D3',
      type: 'door',
      x: 3,
      y: 5,
      enabled: true,
      isOpen: true,
    },
    {
      id: 'T3',
      type: 'turret',
      x: 8,
      y: 2,
      enabled: true,
      range: 7,
      lockDelay: 3,
      alarmTrigger: 'DETECTION',
      desiredTargetId: null,
      currentTargetId: null,
      lockTicks: 0,
    },
    {
      id: 'A3',
      type: 'alarm',
      x: 0,
      y: 0,
      enabled: true,
      state: 'GREEN',
      baseEscalationTicks: 3,
      redAtTick: null,
      manualDelayBuffer: 0,
    },
    {
      id: 'TERM3',
      type: 'terminal',
      x: 1,
      y: 7,
      enabled: true,
    },
  ],
  networkScope: ['C3', 'D3'],
  constraints: {
    tickLimit: 70,
  },
};
